/**
 * Actions
 */

// Modes
export const SET_MAP_MODE = 'SET_MAP_MODE';
export const SET_MODE = 'SET_MODE';
export const LOAD = 'LOAD';

// Single points
export const ADD_SINGLE_POINT = 'ADD_SINGLE_POINT';
export const SELECT_SINGLE_POINT = 'SELECT_SINGLE_POINT';
export const SET_SINGLE_POINT_NOTE = 'SET_SINGLE_POINT_NOTE';
export const SET_SINGLE_POINT_NAME = 'SET_SINGLE_POINT_NAME';

// Trajectories
export const SELECT_TRAJECTORY = 'SELECT_TRAJECTORY';
export const SELECT_TRAJECTORY_POINT = 'SELECT_TRAJECTORY_POINT';
export const SET_TRAJECTORY_NAME = 'SET_TRAJECTORY_NAME';
export const SET_TRAJECTORY_NOTES = 'SET_TRAJECTORY_NOTES';
export const ADD_POINT_TO_TRAJECTORY = 'ADD_POINT_TO_TRAJECTORY';
export const SET_TRAJECTORY_POINT_NAME = 'SET_TRAJECTORY_POINT_NAME';
export const SET_TRAJECTORY_POINT_NOTES = 'SET_TRAJECTORY_POINT_NOTES';

// Reset
export const SET_START_RESETTING = 'SET_START_RESETTING';
export const SET_RESETED = 'SET_RESETED';

// Save
export const SET_START_SAVING = 'SET_START_SAVING';
export const SET_SAVED = 'SET_SAVED';

// Export
export const SET_START_EXPORTING = 'SET_START_EXPORTING';
export const SET_EXPORTED = 'SET_EXPORTED';

